### ISSUE TITLE
dotnet install tool issue

### ISSUE THREAD

**Issue by cybercussion** [gfoidl/trx2junit#11] opened 2018-08-22 20:12 UTC
So I had to `dotnet install tool -g --version '1.0.2' trx2junit` to get it to work.  Kept saying / complaining about being in preview mode.  Just a FYI if anyone has the issue.

**Comment by gfoidl** [comment] 2018-08-23 11:48
@cybercussion thanks for reporting. I'll have a look and fix this.

**Comment by gfoidl** [comment] 2018-08-23 12:05
@cybercussion what version of the .NET SDK do you use (`dotnet --info`). With current versions the tools installs (`dotnet tool install -g trx2junit`) just fine and runs without any problems. Maybe you use a preview of the SDK.

**Comment by cybercussion** [comment] 2018-08-23 13:29
I believe it was 2.1.335 after I updated it yesterday.  But its possible I pulled down a beta.

**Comment by gfoidl** [comment] 2018-08-23 13:53
Can you please verify that it works as expected?

```bash
dotnet tool uninstall -g trx2junit
dotnet tool install -g trx2junit
```

So the issue could be closed, or if not working as expected so I can fix this.

**Comment by cybercussion** [comment] 2018-08-23 14:01
I can do that first thing tomorrow morning.  I think we are good though.  I was just setting up a gitlab runner on a slave box and 11.2 will be able to read the jUnit format so I appreciate your conversion.

**Comment by cybercussion** [comment] 2018-08-27 16:38
2.1.401

```
dotnet tool install -g trx2junit
C:\Program Files\dotnet\sdk\2.1.401\NuGet.targets(114,5): error : Failed to retrieve information about 'trx2junit' from remote source 'https://tb-nugtapp-d101/TrueGet/dev/nuget/FindPackagesById()?id='trx2junit'&semVerLevel=2.0.0'. [C:\Users\mstatkus.CORP\AppData\Local\Temp\d5kkll30.c5c\restore.csproj]
C:\Program Files\dotnet\sdk\2.1.401\NuGet.targets(114,5): error :   No connection could be made because the target machine actively refused it [C:\Users\mstatkus.CORP\AppData\Local\Temp\d5kkll30.c5c\restore.csproj]
The tool package could not be restored.
Tool 'trx2junit' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET Core tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.
```

re-did with `dotnet tool install -g --version '1.0.2' trx2junit` and it worked.

**Comment by gfoidl** [comment] 2018-08-27 18:37
In a fresh linux-vm with .NET SDK 2.1.401 I can't reproduce this. The installation just runs fine.

> `Failed to retrieve information about 'trx2junit' from remote source 'https://tb-nugtapp-d101/TrueGet/dev/nuget/FindPackagesById()?id='trx2junit'&semVerLevel=2.0.0'`
Looks suspicious to me, because this is not the standard nuget-source. So it might be that in this feed no package matching `trx2junit` is found.
Do you have any special nuget-feeds / sources registered?

Can you please run
```bash
dotnet tool install -g trx2junit -v d | tee res.txt
```
and attach the `res.txt`-file? This contains quite a lot info about the build and installation. Maybe this way the source of the misebehaviour can be tracked down.

**Comment by gfoidl** [comment] 2018-09-13 18:29
@cybercussion I'm closing this issue. It it is still active, please feel free to reopen it.

**Closed as completed** 2018-09-14 11:22 UTC
Labels: bug, not-reproducable
